# Generated by mix zen_cex.generate_endpoints binance
# DO NOT EDIT - Regenerate using: mix zen_cex.generate_endpoints binance

[
  %{
    operation: :get_account,
    method: :get,
    path: "/api/v3/account",
    requires_auth: true,
    weight: 20,
    timeout: 5000,
    max_retries: 3,
    retry_on: [:rate_limited, :timeout, :server_error],
    response_parser: &Parser.parse_account/1,
    error_mapping: &Parser.parse_error/1,
    doc: "Account Information (USER_DATA)

Get current account information.

Weight(IP): 20"
  },
  %{
    operation: :"get_account/commission",
    method: :get,
    path: "/api/v3/account/commission",
    requires_auth: true,
    weight: 1,
    timeout: 5000,
    max_retries: 3,
    retry_on: [:rate_limited, :timeout, :server_error],
    response_parser: &Parser.parse_account/1,
    error_mapping: &Parser.parse_error/1,
    doc: "Query Commission Rates (USER_DATA)

Get current account commission rates.

Weight: 20"
  },
  %{
    operation: :get_allOrderList,
    method: :get,
    path: "/api/v3/allOrderList",
    requires_auth: true,
    weight: 20,
    timeout: 5000,
    max_retries: 3,
    retry_on: [:rate_limited, :timeout, :server_error],
    response_parser: &Parser.parse_generic/1,
    error_mapping: &Parser.parse_error/1,
    doc: "Query all OCO (USER_DATA)

Retrieves all OCO based on provided optional parameters

Weight(IP): 20"
  },
  %{
    operation: :get_allOrders,
    method: :get,
    path: "/api/v3/allOrders",
    requires_auth: true,
    weight: 20,
    timeout: 5000,
    max_retries: 3,
    retry_on: [:rate_limited, :timeout, :server_error],
    response_parser: &Parser.parse_generic/1,
    error_mapping: &Parser.parse_error/1,
    doc: "All Orders (USER_DATA)

Get all account orders; active, canceled, or filled..

- If `orderId` is set, it will get orders >= that `orderId`. Otherwise most recent orders are returned.
- For some historical orders `cummulativeQuoteQty` will be < 0, meaning the data is not available at this time.
- If `startTime` and/or `endTime` provided, `orderId` is not required

Weight(IP): 20"
  },
  %{
    operation: :get_myTrades,
    method: :get,
    path: "/api/v3/myTrades",
    requires_auth: true,
    weight: 20,
    timeout: 5000,
    max_retries: 3,
    retry_on: [:rate_limited, :timeout, :server_error],
    response_parser: &Parser.parse_trades/1,
    error_mapping: &Parser.parse_error/1,
    doc: "Account Trade List (USER_DATA)

Get trades for a specific account and symbol.

If `fromId` is set, it will get id >= that `fromId`. Otherwise most recent orders are returned.

The time between startTime and endTime can't be longer than 24 hours.
These are the supported combinations of all parameters:

  symbol

  symbol + orderId

  symbol + startTime

  symbol + endTime

  symbol + fromId

  symbol + startTime + endTime

  symbol+ orderId + fromId

Weight(IP): 20"
  },
  %{
    operation: :delete_openOrders,
    method: :delete,
    path: "/api/v3/openOrders",
    requires_auth: true,
    weight: 1,
    timeout: 5000,
    max_retries: 1,
    retry_on: [:timeout],
    response_parser: &Parser.parse_generic/1,
    error_mapping: &Parser.parse_error/1,
    doc: "Cancel all Open Orders on a Symbol (TRADE)

Cancels all active orders on a symbol.
This includes OCO orders.

Weight(IP): 1"
  },
  %{
    operation: :get_openOrders,
    method: :get,
    path: "/api/v3/openOrders",
    requires_auth: true,
    weight: 1,
    timeout: 5000,
    max_retries: 3,
    retry_on: [:rate_limited, :timeout, :server_error],
    response_parser: &Parser.parse_generic/1,
    error_mapping: &Parser.parse_error/1,
    doc: "Current Open Orders (USER_DATA)

Get all open orders on a symbol. Careful when accessing this with no symbol.

Weight(IP):
- `6` for a single symbol;
- `80` when the symbol parameter is omitted;"
  },
  %{
    operation: :cancel_order,
    method: :delete,
    path: "/api/v3/order",
    requires_auth: true,
    weight: 1,
    timeout: 2000,
    max_retries: 1,
    retry_on: [:timeout],
    response_parser: &Parser.parse_order/1,
    error_mapping: &Parser.parse_error/1,
    doc: "Cancel Order (TRADE)

Cancel an active order.

Either `orderId` or `origClientOrderId` must be sent.

Weight(IP): 1"
  },
  %{
    operation: :get_order,
    method: :get,
    path: "/api/v3/order",
    requires_auth: true,
    weight: 4,
    timeout: 5000,
    max_retries: 3,
    retry_on: [:rate_limited, :timeout, :server_error],
    response_parser: &Parser.parse_order/1,
    error_mapping: &Parser.parse_error/1,
    doc: "Query Order (USER_DATA)

Check an order's status.

- Either `orderId` or `origClientOrderId` must be sent.
- For some historical orders `cummulativeQuoteQty` will be < 0, meaning the data is not available at this time.

Weight(IP): 4"
  },
  %{
    operation: :place_order,
    method: :post,
    path: "/api/v3/order",
    requires_auth: true,
    weight: 1,
    timeout: 2000,
    max_retries: 0,
    retry_on: [],
    response_parser: &Parser.parse_order/1,
    error_mapping: &Parser.parse_error/1,
    doc: "New Order (TRADE)

Send in a new order.

- `LIMIT_MAKER` are `LIMIT` orders that will be rejected if they would immediately match and trade as a taker.
- `STOP_LOSS` and `TAKE_PROFIT` will execute a `MARKET` order when the `stopPrice` is reached.
- Any `LIMIT` or `LIMIT_MAKER` type order can be made an iceberg order by sending an `icebergQty`.
- Any order with an `icebergQty` MUST have `timeInForce` set to `GTC`.
- `MARKET` orders using `quantity` specifies how much a user wants to buy or sell based on the market price.
- `MARKET` orders using `quoteOrderQty` specifies the amount the user wants to spend (when buying) or receive (when selling) of the quote asset; the correct quantity will be determined based on the market liquidity and `quoteOrderQty`.
- `MARKET` orders using `quoteOrderQty` will not break `LOT_SIZE` filter rules; the order will execute a quantity that will have the notional value as close as possible to `quoteOrderQty`.
- same `newClientOrderId` can be accepted only when the previous one is filled, otherwise the order will be rejected.

Trigger order price rules against market price for both `MARKET` and `LIMIT` versions:

- Price above market price: `STOP_LOSS` `BUY`, `TAKE_PROFIT` `SELL`
- Price below market price: `STOP_LOSS` `SELL`, `TAKE_PROFIT` `BUY`


Weight(IP): 1"
  },
  %{
    operation: :cancel_orderList,
    method: :delete,
    path: "/api/v3/orderList",
    requires_auth: true,
    weight: 1,
    timeout: 5000,
    max_retries: 1,
    retry_on: [:timeout],
    response_parser: &Parser.parse_order/1,
    error_mapping: &Parser.parse_error/1,
    doc: "Cancel OCO (TRADE)

Cancel an entire Order List

Canceling an individual leg will cancel the entire OCO

Weight(IP): 1"
  },
  %{
    operation: :get_orderList,
    method: :get,
    path: "/api/v3/orderList",
    requires_auth: true,
    weight: 4,
    timeout: 5000,
    max_retries: 3,
    retry_on: [:rate_limited, :timeout, :server_error],
    response_parser: &Parser.parse_order/1,
    error_mapping: &Parser.parse_error/1,
    doc: "Query OCO (USER_DATA)

Retrieves a specific OCO based on provided optional parameters

Weight(IP): 4"
  },
  %{
    operation: :"place_orderList/oco",
    method: :post,
    path: "/api/v3/orderList/oco",
    requires_auth: true,
    weight: 1,
    timeout: 5000,
    max_retries: 1,
    retry_on: [:timeout],
    response_parser: &Parser.parse_order/1,
    error_mapping: &Parser.parse_error/1,
    doc: "New Order list - OCO (TRADE)

Send in an one-cancels-the-other (OCO) pair, where activation of one order immediately cancels the other.

- An `OCO` has 2 orders called the above order and below order.
- One of the orders must be a `LIMIT_MAKER` order and the other must be `STOP_LOSS` or`STOP_LOSS_LIMIT` order.
- Price restrictions:
    - If the `OCO` is on the `SELL` side: `LIMIT_MAKER` price > Last Traded Price > stopPrice
    - If the `OCO` is on the `BUY` side: `LIMIT_MAKER` price < Last Traded Price < stopPrice
- OCOs add 2 orders to the unfilled order count, `EXCHANGE_MAX_ORDERS` filter, and the `MAX_NUM_ORDERS` filter.

Weight(IP): 1"
  },
  %{
    operation: :"place_orderList/oto",
    method: :post,
    path: "/api/v3/orderList/oto",
    requires_auth: true,
    weight: 1,
    timeout: 5000,
    max_retries: 1,
    retry_on: [:timeout],
    response_parser: &Parser.parse_order/1,
    error_mapping: &Parser.parse_error/1,
    doc: "New Order List - OTO (TRADE)

Places an `OTO`.
- An `OTO` (One-Triggers-the-Other) is an order list comprised of 2 orders.
- The first order is called the working order and must be `LIMIT` or `LIMIT_MAKER`. Initially, only the working order goes on the order book.
- The second order is called the pending order. It can be any order type except for `MARKET` orders using parameter `quoteOrderQty`. The pending order is only placed on the order book when the working order gets fully filled.
- If either the working order or the pending order is cancelled individually, the other order in the order list will also be canceled or expired.
- When the order list is placed, if the working order gets immediately fully filled, the placement response will show the working order as `FILLED` but the pending order will still appear as `PENDING_NEW`. You need to query the status of the pending order again to see its updated status.
- OTOs add 2 orders to the unfilled order count, `EXCHANGE_MAX_NUM_ORDERS` filter and `MAX_NUM_ORDERS` filter.

Weight: 1"
  },
  %{
    operation: :"place_orderList/otoco",
    method: :post,
    path: "/api/v3/orderList/otoco",
    requires_auth: true,
    weight: 1,
    timeout: 5000,
    max_retries: 1,
    retry_on: [:timeout],
    response_parser: &Parser.parse_order/1,
    error_mapping: &Parser.parse_error/1,
    doc: "New Order List - OTOCO (TRADE)

Place an `OTOCO`.
- An `OTOCO` (One-Triggers-One-Cancels-the-Other) is an order list comprised of 3 orders.
- The first order is called the working order and must be `LIMIT` or `LIMIT_MAKER`. Initially, only the working order goes on the order book.
  - The behavior of the working order is the same as the `OTO`.
- `OTOCO` has 2 pending orders (pending above and pending below), forming an `OCO` pair. The pending orders are only placed on the order book when the working order gets fully filled.
  - The rules of the pending above and pending below follow the same rules as the Order List `OCO`.
- OTOCOs add 3 orders against the unfilled order count, `EXCHANGE_MAX_NUM_ORDERS` filter, and `MAX_NUM_ORDERS` filter.

Weight: 1"
  },
  %{
    operation: :get_ping,
    method: :get,
    path: "/api/v3/ping",
    requires_auth: false,
    weight: 1,
    timeout: 5000,
    max_retries: 3,
    retry_on: [:rate_limited, :timeout, :server_error],
    response_parser: &Parser.parse_generic/1,
    error_mapping: &Parser.parse_error/1,
    doc: "Test Connectivity

Test connectivity to the Rest API.

Weight(IP): 1"
  },
  %{
    operation: :get_time,
    method: :get,
    path: "/api/v3/time",
    requires_auth: false,
    weight: 1,
    timeout: 5000,
    max_retries: 3,
    retry_on: [:rate_limited, :timeout, :server_error],
    response_parser: &Parser.parse_generic/1,
    error_mapping: &Parser.parse_error/1,
    doc: "Check Server Time

Test connectivity to the Rest API and get the current server time.

Weight(IP): 1"
  }
]
